# nixpacks.toml
[phases.setup]
nixPkgs = ['...', 'python3', 'opencv', 'libGL']
aptPkgs = ['...', 'libgl1', 'libgl1-mesa-dev', 'libgl1-mesa-dri', 'libgl1-mesa-glx:i386']

[start]
cmd = "gunicorn app:app"
